name: Checks

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    python-unit:
        timeout-minutes: 1
        name: Python Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: python
        steps:
            - uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: "0.6.12"
            - name: Install dependencies
              run: uv sync --all-extras
            - name: Run Tests
              run: uv run pytest tests
    typescript-tests:
        timeout-minutes: 1
        name: Typescript Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "pnpm"
            - name: Install pnpm dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Tests
              run: pnpm --filter mcp-webrtc run test
